# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# if [[ -f "/opt/homebrew/bin/brew" ]] then
#   # If you're using macOS, you'll want this enabled
#   eval "$(/opt/homebrew/bin/brew shellenv)"
# fi

# Set the directory we want to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Add in Powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k
zinit ice pick'poetry.zsh'

# Add in zsh plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab
zinit light sudosubin/zsh-poetry

# Add in snippets
zinit snippet OMZL::git.zsh
zinit snippet OMZP::git
zinit snippet OMZP::sudo
zinit snippet OMZP::ubuntu
zinit snippet OMZP::aws
zinit snippet OMZP::kubectl
zinit snippet OMZP::kubectx
zinit snippet OMZP::command-not-found

# Load completions
autoload -Uz compinit && compinit

zinit cdreplay -q

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Keybindings
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^[w' kill-region

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# Aliases
alias ls='ls --color'
alias vim='nvim'
alias c='clear'
alias bat='batcat'
alias kbfix='ibus restart'
alias upd='sudo apt update -y && sudo apt upgrade -y && sudo snap refresh && flatpak update --assumeyes'
alias dot='/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME'

# Custom Path 
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# === Claude Code Configuration (Start) ===
# Generated by Claude Code installer on 2025-09-11

# Add Claude Code CLI to PATH
export PATH="/home/udmehrot/.claude-code-cli/bin:$PATH"

# === Claude Code Configuration (End) ===


# === Claude Code Aliases (Start) ===
# Generated by Claude Code installer on 2025-09-11
# Convenient aliases for Claude Code with different AWS profiles and regions

# Remove any existing ccs alias to avoid conflicts with function
type ccs >/dev/null 2>&1 && unalias ccs 2>/dev/null || true

# Interactive Claude Code menu function
ccs() {
    echo ""
    echo "🚀 Claude Code - Select AWS Profile & Region:"
    echo ""
    echo "  1) devops-105 + us-east-1    (ccs1)"
    echo "  2) devops-105 + us-east-2    (ccs2)" 
    echo "  3) devops-105 + us-west-2    (ccs3)"
    echo "  4) devops-586 + us-east-1    (ccs4)"
    echo "  5) devops-586 + us-east-2    (ccs5)"
    echo "  6) devops-586 + us-west-2    (ccs6)"
    echo ""
    echo "  q) Quit"
    echo ""
    
    local choice
    while true; do
        if [[ -n "${ZSH_VERSION:-}" ]]; then
            read "choice?Choose an option (1-6 or q): "
        else
            read -p "Choose an option (1-6 or q): " choice
        fi
        case "$choice" in
            1) echo ""; echo "🎯 Launching with devops-105 + us-east-1..."; eval ccs1 "$@"; return ;;
            2) echo ""; echo "🎯 Launching with devops-105 + us-east-2..."; eval ccs2 "$@"; return ;;
            3) echo ""; echo "🎯 Launching with devops-105 + us-west-2..."; eval ccs3 "$@"; return ;;
            4) echo ""; echo "🎯 Launching with devops-586 + us-east-1..."; eval ccs4 "$@"; return ;;
            5) echo ""; echo "🎯 Launching with devops-586 + us-east-2..."; eval ccs5 "$@"; return ;;
            6) echo ""; echo "🎯 Launching with devops-586 + us-west-2..."; eval ccs6 "$@"; return ;;
            q|Q) echo ""; echo "👋 Goodbye!"; return ;;
            *) echo "❌ Invalid choice. Please enter 1-6 or q." ;;
        esac
    done
}

# Claude CLI alias for local installation

alias ccs1='AWS_PROFILE="devops-105" AWS_REGION="us-east-1" claude-code-safe'
alias ccs2='AWS_PROFILE="devops-105" AWS_REGION="us-east-2" claude-code-safe'
alias ccs3='AWS_PROFILE="devops-105" AWS_REGION="us-west-2" claude-code-safe'
alias ccs4='AWS_PROFILE="devops-586" AWS_REGION="us-east-1" claude-code-safe'
alias ccs5='AWS_PROFILE="devops-586" AWS_REGION="us-east-2" claude-code-safe'
alias ccs6='AWS_PROFILE="devops-586" AWS_REGION="us-west-2" claude-code-safe'
# === Claude Code Aliases (End) ===

export SUDO_EDITOR="/snap/bin/nvim"
